### ISSUE TITLE
maybe an issue with this, idk how to understand tbh

### ISSUE THREAD

**Issue by superon** [alkyaly/Infinity-Water-Bucket#2]
i've been experiencing this server crash which may or may not be directly or indirectly linked to this mod
infinity-water-bucket-1.0.1-mc1.16.4-fabric
https://pastebin.com/XrahbB7u

note that i'm not using InfinityFix and i'm currently in the process of refining the pack mods in attempt to work out exactly what's causing this crash

**Comment by alkyaly** [comment]
Traced the error, it's caused by [Durability Banks](https://github.com/dzwdz/durability_banks/blob/master/src/main/java/dzwdz/durability_banks/mixin/EnchantmentMixin.java), not by Infinity Water Bucket

**Comment by superon** [comment]
oh wow, thanks, thanks wasn't even on my list of possibilities :/

**Comment by alkyaly** [comment]
Omg i was wrong, it was indeed caused by my mod, anyway i fixed it
