### ISSUE TITLE
Infinity water bucket is emptied when used to fill a Petal Apothecary from Botania

### ISSUE THREAD

**Issue by chimericdream** [alkyaly/Infinity-Water-Bucket#7]
Pretty much what the title says. When I use the infinity bucket on a petal apothecary, it gets emptied out like normal. The infinity enchantment doesn't get removed, so that is good. But it becomes an infinitely empty bucket instead.

**Comment by coolsimulations** [comment]
This is isn't too big of an issue to make a patch for. There are other cases now for converting an empty infinity bucket to a filled one
