### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by EliteMasterEric** [alkyaly/Infinity-Water-Bucket#8]
This codebase has no license specified. It is open source but currently All Rights Reserved.

I recommend the LGPL license, since this requires any derivatives be open source. Permissive licenses work better for codebases that may eventually become part of commercial products but Minecraft mods can't be commercialized.

**Comment by coolsimulations** [comment]
Probably right, honestly the license is an afterthought. Don't want public forks is the main concern hence All Rights Reserved. It's opened source here though for the sake of transparency and mod compats.
