### ISSUE TITLE
Modpack incompatibility with GTNH

### ISSUE THREAD

**Issue by shadow7483147** [alkyaly/Infinity-Water-Bucket#9]
Attempting to add this mod to Gregtech New Horizons 2.3.2 (Java 17) crashes when launching.
[clipboard.txt](https://github.com/coolsimulations/Infinity-Water-Bucket/files/11300459/clipboard.txt)

**Comment by coolsimulations** [comment]
1.7.10 is pre-mixin, so any other mod that uses mixin or some ASM change is highly incompatible if we edit the same classes. Nothing I can do for this

**Comment by shadow7483147** [comment]
ha, ok.

I don’t remember making this issue. It reads like a pretty stupid one in retrospect. My apologies.
